name: Deploy Angular from Artifact Registry to S3

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version to deploy (leave empty for latest)"
        required: false
  push:
    branches:
      - server

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/297178011153/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "doqfy-storage@crucial-context-454812-v3.iam.gserviceaccount.com"
          project_id: "crucial-context-454812-v3"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: crucial-context-454812-v3

      - name: Configure gcloud
        run: gcloud config set project crucial-context-454812-v3

      - name: Determine Deployment Version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            SELECTED_VERSION="${{ github.event.inputs.version }}"
          else
            SELECTED_VERSION=$(gcloud artifacts versions list \
              --repository=auth-gateway-frontend-cicd \
              --location=us-west2 \
              --package=auth-frontend \
              --project=crucial-context-454812-v3 \
              --sort-by=~CREATE_TIME \
              --limit=1 \
              --format='value(name)')
          fi
          echo "SELECTED_VERSION=$SELECTED_VERSION" >> $GITHUB_ENV

      - name: Ensure Download Directory Exists
        run: mkdir -p downloaded_package

      - name: Find Package File for Selected Version
        run: |
          SELECTED_FILE=$(gcloud artifacts files list \
            --repository=auth-gateway-frontend-cicd \
            --location=us-west2 \
            --package=auth-frontend \
            --version=$SELECTED_VERSION \
            --project=crucial-context-454812-v3 \
            --sort-by=~CREATE_TIME \
            --limit=1 \
            --format='value(name)')
          echo "SELECTED_FILE=$SELECTED_FILE" >> $GITHUB_ENV

      - name: Download Selected Package
        run: |
          gcloud artifacts files download "$SELECTED_FILE" \
            --repository=auth-gateway-frontend-cicd \
            --location=us-west2 \
            --project=crucial-context-454812-v3 \
            --destination=downloaded_package/

      - name: Rename Downloaded Package
        run: |
          ACTUAL_FILE=$(ls downloaded_package/ | grep "$(basename "$SELECTED_FILE" | sed 's/%2F/\//g')")
          if [ -z "$ACTUAL_FILE" ]; then
            echo "Error: Downloaded file not found!"
            exit 1
          fi
          mv "downloaded_package/$ACTUAL_FILE" "downloaded_package/frontend-${{ env.SELECTED_VERSION }}.tgz"

      - name: Extract Package
        run: |
          tar -xzf downloaded_package/frontend-${{ env.SELECTED_VERSION }}.tgz -C downloaded_package/
          ls -l downloaded_package/

      - name: Locate Dist Folder
        run: |
          DIST_PATH=$(find downloaded_package -type d -name "dist" -print -quit)
          if [ -z "$DIST_PATH" ]; then
            echo "Error: 'dist' folder not found!"
            exit 1
          fi
          echo "DIST_PATH=$DIST_PATH" >> $GITHUB_ENV

      - name: Add PEM Key for SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ~/.ssh/auth-gateway.pem
          chmod 600 ~/.ssh/auth-gateway.pem

      - name: Copy Files to Google VM
        run: |
          scp -i ~/.ssh/auth-gateway.pem -o StrictHostKeyChecking=no -r "${{ env.DIST_PATH }}/auth-portal" Rwoqbanuswoambn@35.207.203.13:/tmp/frontend-${{ env.SELECTED_VERSION }}

      - name: Deploy Files on Google VM
        run: |
          ssh -i ~/.ssh/auth-gateway.pem -o StrictHostKeyChecking=no Rwoqbanuswoambn@35.207.203.13 << 'EOF'
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/frontend-${{ env.SELECTED_VERSION }}/* /var/www/html/
            sudo rm -rf /tmp/frontend-${{ env.SELECTED_VERSION }}
            echo "✅ Deployment complete."
          EOF
