name: Deploy Auth Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud authentication
        run: |
          gcloud auth configure-docker us-west2-docker.pkg.dev
          gcloud auth application-default print-access-token > access-token.txt

      - name: Set up NPM for Artifact Registry
        run: |
          npm config set '//us-west2-npm.pkg.dev/:_authToken' "$(gcloud auth print-access-token)"

      - name: Verify authentication
        run: gcloud auth list

      - name: Download artifact from Artifact Registry
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          curl -H "Authorization: Bearer $ACCESS_TOKEN" \
               -o auth-frontend.tgz \
               "https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend-cicd/auth-frontend/-/auth-frontend-0.0.9.tgz"

          if [ ! -s auth-frontend.tgz ]; then
            echo "❌ Error: Downloaded file is empty or corrupted."
            exit 1
          fi

      - name: Extract Artifact
        run: |
          mkdir -p auth-frontend
          tar -xzf auth-frontend.tgz -C auth-frontend --strip-components=1

      - name: Deploy (Customize this step)
        run: |
          echo "🚀 Deploying the application..."
