name: Deploy Angular from Artifact Registry to GCS

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: gcloud config set project crucial-context-454812-v3

      - name: Find Latest Version of `auth-frontend`
        run: |
          LATEST_VERSION=$(gcloud artifacts versions list \
            --package=auth-frontend \
            --repository=auth-gateway-frontend-cicd \
            --location=us-west2 \
            --sort-by="~CREATE_TIME" \
            --limit=1 \
            --format="value(name)")

          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Download Latest Package
        run: |
          set -x
          mkdir -p downloaded_package
          FILE_PATH="auth-frontend/${LATEST_VERSION}/auth-frontend-${LATEST_VERSION}.tgz"

          gcloud artifacts files download "$FILE_PATH" \
            --repository=auth-gateway-frontend-cicd \
            --location=us-west2 \
            --destination=downloaded_package/

      - name: Upload Package to GCS
        run: |
          gsutil cp downloaded_package/auth-frontend-${LATEST_VERSION}.tgz gs://your-bucket-name/

      - name: Print Deployment URL
        run: echo "Package uploaded to: gs://your-bucket-name/auth-frontend-${LATEST_VERSION}.tgz"
