name: Build and Deploy Angular App

on:
  push:
    branches:
      - master
      - dev
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend/'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install Webpack
        run: npm install webpack --save-dev

      - name: Build Angular App
        run: npm run build --omit=dev

      - name: Verify Build Artifacts
        run: ls -lah ./dist

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload Build to Artifact Registry
        run: |
          npm publish --registry=https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend/
