name: Build and Publish Angular App to Google Artifact Registry (NPM)

on:
  push:
    branches:
      - master
      - dev
      - staging
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend/"

      - name: Install Dependencies
        run: npm install --force

      - name: Build Angular App
        run: npm run build --prod

      - name: Verify Build Output
        run: ls -lah ./dist/auth-portal

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure NPM Authentication
        run: |
          echo "//us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend/:_authToken=$(gcloud auth print-access-token)" > ~/.npmrc

      - name: Package and Publish to Google Artifact Registry (NPM)
        run: |
          mkdir -p ./package
          cp -r ./dist/auth-portal ./package
          echo '{ "name": "@crucial-context/auth-gateway-frontend", "version": "1.0.${{ github.run_number }}", "main": "index.html" }' > ./package/package.json
          npm publish ./package --registry="https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend/"
