name: Debug GCS Authentication

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  push:
    branches:
      - master  # Runs on push to master

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: crucial-context-454812-v3  # Replace with your project ID

      - name: Verify Authentication
        run: |
          echo "Checking authentication..."
          gcloud auth list
          gcloud config list
          gcloud projects list
          gsutil config list

      - name: Check GCS Access
        run: |
          echo "Listing buckets..."
          gcloud storage buckets list
