name: Build and Deploy Angular App

on:
  push:
    branches:
      - master
      - dev
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure NPM Authentication
        run: echo "//us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Project
        run: npm run build --prod

      - name: Verify Build Artifacts
        run: ls -lah dist/

      - name: Publish to Google Artifact Registry
        run: npm publish --registry=https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
