name: Debug GCS Authentication

on:
  workflow_dispatch  # Allows manual triggering

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Verify Authentication
        run: |
          echo "Checking authentication..."
          gcloud auth list
          gcloud config list
          gcloud projects list
          gsutil config list

      - name: Check GCS Access
        run: |
          echo "Listing buckets..."
          gcloud storage buckets list
