name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: crucial-context-454812-v3
      REPO_NAME: auth-gateway-frontend
      REGION: us-west2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure NPM Authentication for Artifact Registry
        run: |
          echo "//${{ env.REGION }}-npm.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/:_authToken=$(gcloud auth print-access-token)" > ~/.npmrc
          cat ~/.npmrc

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular App
        run: npm run build --prod

      - name: Deploy to GCP Storage (Optional)
        run: |
          gsutil -m rsync -r dist gs://your-gcs-bucket-name
