name: CI/CD Pipeline

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build-push-artifactory:
    name: Build and Push to Artifact Registry
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: crucial-context-454812-v3
      REPO_NAME: auth-final
      REGION: us-west2
      ARTIFACT_REGISTRY: us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-final

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --force

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Removing the dist file
        run: rm -rf dist/

      - name: Build Angular Project
        run: npx ng build --configuration=production

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure npm for Artifact Registry
        run: |
          npm set @crucial-context-454812-v3:registry=https://${{ env.ARTIFACT_REGISTRY }}/
          npm set //${{ env.ARTIFACT_REGISTRY }}/:_authToken="$(gcloud auth print-access-token)"

      - name: Temporarily Disable Private Flag
        run: jq 'del(.private)' package.json > temp.json && mv temp.json package.json

      - name: Clear npm Cache
        run: npm cache clean --force

      - name: Fetch Latest Version and Increment
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          echo "Fetching versions for $PACKAGE_NAME from registry..."

          PUBLISHED_VERSIONS=$(npm view $PACKAGE_NAME versions --json --registry=https://${{ env.ARTIFACT_REGISTRY }}/ 2>/dev/null || echo "[]")

          # Convert JSON list to newline-separated versions, remove brackets and quotes
          PUBLISHED_VERSIONS=$(echo "$PUBLISHED_VERSIONS" | tr -d '[]"' | tr ',' '\n')

          # Check if we got versions or need to start from 0.0.1
          if [[ -z "$PUBLISHED_VERSIONS" ]]; then
            LATEST_VERSION="0.0.0"
          else
            LATEST_VERSION=$(echo "$PUBLISHED_VERSIONS" | sort -V | tail -n 1)
          fi

          # Extract and increment the patch version (0.0.X)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"

          echo "New version to be published: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
          npm version "$NEW_VERSION" --no-git-tag-version
          echo "Updated package.json version to $NEW_VERSION"

      - name: Publish Latest Version
        run: |
          echo "Publishing version: $NEW_VERSION"
          npm publish --registry=https://${{ env.ARTIFACT_REGISTRY }}/ --tag latest
