name: Build and Deploy Angular App using Docker

on:
  push:
    branches:
      - master
      - dev
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version and Branch Name
        id: get_version_branch
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t my-angular-app:latest .

      - name: Run Docker Container
        run: |
          docker run -d --name angular-container my-angular-app:latest tail -f /dev/null

      - name: Copy Build Artifacts from Container
        run: |
          docker cp angular-container:/usr/share/nginx/html/auth-portal ./dist/auth-portal

      - name: Stop and Remove Container
        run: |
          docker stop angular-container
          docker rm angular-container

      - name: Zip Build Artifacts
        run: |
          cd ./dist
          zip -r "latest-${BRANCH}.zip" auth-portal
          zip -r "v${VERSION}-${BRANCH}.zip" auth-portal

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Upload zip files to Google Cloud Storage
      - name: Upload Zip Files to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ./dist/latest-${BRANCH}.zip
          destination: doqfy-auth-gateway-fronend-dist
          gzip: false

      - name: Upload Versioned Zip File to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ./dist/v${VERSION}-${BRANCH}.zip
          destination: doqfy-auth-gateway-fronend-dist
          gzip: false
