name: Build and Deploy Frontend

on:
  push:
    branches:
      - staging

jobs:
  build-deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: crucial-context-454812-v3
      REPO_NAME: auth-gateway-frontend
      REGION: us-west2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure NPM Authentication for Artifact Registry
        run: |
          echo "//${{ env.REGION }}-npm.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/:_authToken=$(gcloud auth print-access-token)" > ~/.npmrc
          cat ~/.npmrc

      - name: Clean Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install webpack webpack-cli @angular-devkit/build-angular --save-dev

      - name: Build Angular App
        run: npm run build --prod

      - name: Deploy to GCP Storage (Optional)
        run: |
          gsutil -m rsync -r dist gs://your-gcs-bucket-name
