name: Deploy Auth Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud auth list
          gcloud auth print-access-token

      - name: List Available Versions (Debugging)
        run: |
          gcloud artifacts packages list \
            --repository=auth-gateway-frontend-cicd \
            --location=us-west2

      - name: Download Prebuilt Frontend
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          curl -v -H "Authorization: Bearer $ACCESS_TOKEN" -o auth-frontend.tgz \
            "https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend-cicd/auth-frontend/-/auth-frontend-0.0.9.tgz"

          ls -lah auth-frontend.tgz  # Check file size
          file auth-frontend.tgz  # Verify it's a valid tarball

      - name: Verify Tarball Integrity
        run: |
          tar -tzf auth-frontend.tgz || echo "Tarball is corrupted!"

      - name: Extract Frontend Build
        run: |
          mkdir auth-frontend
          tar -xzf auth-frontend.tgz -C auth-frontend --strip-components=1

      - name: Deploy to Hosting (if needed)
        run: |
          # Add your deployment steps here
