name: Deploy to Google Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: crucial-context-454812-v3

      - name: Configure npm for Artifact Registry
        run: |
          echo "registry=https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend-cicd/" >> ~/.npmrc
          echo "//us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend-cicd/:_authToken=\$(gcloud auth print-access-token)" >> ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Publish to Google Artifact Registry
        run: npm publish
