name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-push-artifactory:
    name: Build and Push to Artifact Registry
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: crucial-context-454812-v3
      REPO_NAME: auth-gateway-frontend-cicd
      REGION: us-west2
      ARTIFACT_REGISTRY: us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend-cicd
      BUCKET_NAME: doqfy-auth-gateway-frontend-dist
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Download Prebuilt Angular App
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          curl -H "Authorization: Bearer $ACCESS_TOKEN" \
               -o auth-frontend.tgz \
               "https://us-west2-npm.pkg.dev/crucial-context-454812-v3/auth-gateway-frontend-cicd/auth-frontend/-/auth-frontend-0.0.9.tgz"
          mkdir auth-frontend
          tar -xzf auth-frontend.tgz -C auth-frontend --strip-components=1

      - name: Upload to Google Cloud Storage
        run: |
          gsutil -m rsync -R auth-frontend gs://${{ env.BUCKET_NAME }}
          gsutil web set -m index.html -e 404.html gs://${{ env.BUCKET_NAME }}
          gsutil iam ch allUsers:objectViewer gs://${{ env.BUCKET_NAME }}
